#!/bin/bash

session_name="YCMB"

tmux has-session -t $session_name 2>/dev/null
if [ $? -eq 0 ]; then
  echo "tmux session found, recreating"
  tmux kill-session -t $session_name
else
  echo "tmux session not found, creating"
fi

tmux new -d -s $session_name -n main "deploy/run_main"

